#!/bin/bash

function usage {
    echo "This script prints the current machines in use, and who is using them."
    echo "  USAGE: condor_shell [--machine MACHINE | --summary]"
}

# Default values.
MACHINE=""
SUMMARY=""

while [[ $# -gt 0 ]] ;
do
    case $1 in
        --machine)
            MACHINE="${2}"
            shift
            shift
            ;;
        --summary)
            SUMMARY="y"
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Too many positional arguments passed!"
            usage
            exit 1
            ;;
    esac
done


if [ -z "$SUMMARY" ]; then
    condor_q -all -l | awk '/^RemoteHost = .*'"${MACHINE}"'/{printf "\033[1;37m%s\033[0m\t",$3; x=1}x&&/^User = /{printf \
"in use by \033[1;33m%s\033[0m\n",$3; x=0}'
else
    condor_q -all -l | awk '/^RemoteHost = .*'"${MACHINE}"'/{printf "%s\t",$3; x=1}x&&/^User = /{printf "in use by %s\n",\
$3; x=0}' | \
        awk 'BEGIN {OFS=", "} \
             { split($1, arr, "@"); \
	       resource = substr(arr[2], 0, length(arr[2]) - 1); \
	       split($5, arr, "@"); \
	       user = substr(arr[1], 2, length(arr[1])); \
	       key = resource "@" user; \
               if (!(key in unique)) { \
	       	  users[resource] = (users[resource] ? users[resource] OFS : "") user; \
		  unique[key]++; \
	       } \
	     } \
             END { for (r in users) print r "  \tin use by " users[r]; }'
fi
