#!/bin/bash

function usage {
    echo "This script prints the current machines in use, and who is using them."
    echo "  USAGE: condor_shell [--machine MACHINE]"
}

# Default values.
MACHINE="n"
WHOLE_MACHINE="n"
INITIAL_DIR="$(pwd)"

while [[ $# -gt 0 ]] ;
do
    case $1 in
        --machine)
            MACHINE="${2}"
            shift
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Too many positional arguments passed!"
            usage
            exit 1
            ;;
    esac
done


if [ -z ${MACHINE+x} ] ; then
    condor_q -all -l | awk '/^RemoteHost = /{printf "\033[1;37m%s\033[0m\t",$3; x=1}x&&/^User = /{printf "in use by \033[1;33m%s\033[0m\n",$3; x=0}'
else
    condor_q -all -l | awk '/^RemoteHost = .*'"${MACHINE}"'/{printf "\033[1;37m%s\033[0m\t",$3; x=1}x&&/^User = /{printf "in use by \033[1;33m%s\033[0m\n",$3; x=0}'
fi
